Repository cengage/react-magma, pull requests merged in 2021-01, with the labels that each got.

#87 chore: upgrade deps
  packages/react-magma-dom/package-lock.json
  packages/react-magma-dom/package.json
  packages/react-magma-icons/package-lock.json
  packages/react-magma-icons/package.json
  packages/react-magma-landing/package-lock.json
  packages/react-magma-landing/package.json
  packages/react-magma-legacy-selects/package.json
Labels: chore

#88 ci(actions): write comment on PRs with the preview
  .github/workflows/preview.yml
Labels: builds

#123 docs: fixed typos on Noto Serif
  packages/react-magma-docs/src/pages/design/typography.mdx
Labels: documentation
