Repository cengage/react-magma, pull requests merged in 2022-07, with the labels that each got.

#812 docs: clean up docs for all components
  .changeset/docs-cleanup.md
  packages/react-magma-dom/src/components/Alert/index.tsx
  packages/react-magma-dom/src/components/Drawer/Drawer.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/LoadingIndicator/index.tsx
  packages/schema-renderer/src/components/FormTemplate/index.tsx
  website/react-magma-docs/src/pages/api/accordion.mdx
  website/react-magma-docs/src/pages/api/alert.mdx
  website/react-magma-docs/src/pages/api/badge.mdx
  website/react-magma-docs/src/pages/api/banner.mdx
  website/react-magma-docs/src/pages/api/blockquote.mdx
  website/react-magma-docs/src/pages/api/button-group.mdx
  website/react-magma-docs/src/pages/api/button.mdx
  website/react-magma-docs/src/pages/api/checkboxes.mdx
  website/react-magma-docs/src/pages/api/combobox.mdx
  website/react-magma-docs/src/pages/api/datagrid.mdx
  website/react-magma-docs/src/pages/api/date-pickers.mdx
  website/react-magma-docs/src/pages/api/drawer.mdx
  website/react-magma-docs/src/pages/api/dropdown.mdx
  website/react-magma-docs/src/pages/api/dropzone.mdx
  website/react-magma-docs/src/pages/api/form-field-wrapper.mdx
  website/react-magma-docs/src/pages/api/form.mdx
  website/react-magma-docs/src/pages/api/formgroup.mdx
  website/react-magma-docs/src/pages/api/heading.mdx
  website/react-magma-docs/src/pages/api/hyperlink.mdx
  website/react-magma-docs/src/pages/api/icon-button.mdx
  website/react-magma-docs/src/pages/api/icon.mdx
  website/react-magma-docs/src/pages/api/indeterminate.mdx
  website/react-magma-docs/src/pages/api/input.mdx
  website/react-magma-docs/src/pages/api/line-chart.mdx
  website/react-magma-docs/src/pages/api/list.mdx
  website/react-magma-docs/src/pages/api/loading-indicator.mdx
  website/react-magma-docs/src/pages/api/modal.mdx
  website/react-magma-docs/src/pages/api/radio.mdx
  website/react-magma-docs/src/pages/api/table.mdx
  website/react-magma-docs/src/pages/api/tabs.mdx
  website/react-magma-docs/src/pages/api/tag.mdx
  website/react-magma-docs/src/pages/api/theme.mdx
  website/react-magma-docs/src/pages/api/toast.mdx
  website/react-magma-docs/src/pages/api/toggle.mdx
  website/react-magma-docs/src/pages/api/tooltip.mdx
  website/react-magma-docs/src/pages/design/button.mdx
Labels: ready for review

#819 docs: various documentation minor updates
  .changeset/testathon-docs.md
  packages/react-magma-dom/src/components/Drawer/Drawer.tsx
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.stories.tsx
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/IconButton/IconButton.stories.tsx
  packages/react-magma-dom/src/components/List/List.stories.tsx
  packages/react-magma-dom/src/components/List/List.tsx
  packages/react-magma-dom/src/components/LoadingIndicator/LoadingIndicator.stories.tsx
  packages/react-magma-dom/src/components/PasswordInput/PasswordInput.stories.tsx
  packages/react-magma-dom/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/react-magma-dom/src/components/Search/Search.stories.tsx
  packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
  packages/react-magma-dom/src/components/TimePicker/TimePicker.stories.tsx
  website/react-magma-docs/src/pages/api/accordion.mdx
  website/react-magma-docs/src/pages/api/form-field-wrapper.mdx
  website/react-magma-docs/src/pages/api/table.mdx
  website/react-magma-docs/src/pages/api/tabs.mdx
  website/react-magma-docs/src/pages/api/tag.mdx
  website/react-magma-docs/src/pages/api/toggle.mdx
  website/react-magma-docs/src/pages/api/use-focus-lock.mdx
  website/react-magma-docs/src/pages/design/tag.mdx
Labels: ready for review, needs-design-feedback

#814 dropdown: remove deprecated prop `onBeforeShiftFocus`
  .changeset/remove-deprecation.md
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
  website/react-magma-docs/src/pages/api/dropdown.mdx
Labels: ready for review

#825 docs: updated pdf file
  .changeset/flat-mugs-chew.md
  website/react-magma-docs/src/downloads/contributing-to-react-magma.pdf
  website/react-magma-docs/static/downloads/contributing-to-react-magma.pdf
Labels: react-magma-docs, RM 3

#822 feat(buttongroup): add `Dropdown` support
  .changeset/buttongroup-dropdown.md
  packages/react-magma-dom/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/react-magma-dom/src/components/ButtonGroup/ButtonGroup.test.js
  packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  packages/react-magma-dom/src/components/ButtonGroup/index.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
  website/react-magma-docs/src/pages/api/button-group.mdx
  website/react-magma-docs/src/pages/api/button.mdx
  website/react-magma-docs/src/pages/api/dropdown.mdx
Labels: ready for review

#826 feat(table): remove `hasOuterBorder` prop and update TablePagination to support `isInverse`
  .changeset/remove-table-outline.md
  .changeset/table-border-conflict.md
  .changeset/tables-border.md
  packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
  packages/react-magma-dom/src/components/Table/Table.stories.tsx
  packages/react-magma-dom/src/components/Table/Table.test.js
  packages/react-magma-dom/src/components/Table/Table.tsx
  packages/react-magma-dom/src/components/Table/TablePagination.tsx
  website/react-magma-docs/src/pages/api/table.mdx
Labels: ready for review

#832 fix(nativeselect): add background color to the options for `isInverse`
  .changeset/native-select-windows.md
  packages/react-magma-dom/src/components/Banner/Banner.stories.tsx
  packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
Labels: ready for review, needs-design-feedback

#835 docs(datagrid): update Datagrid `Row Colors` example
  .changeset/datagrid-docs.md
  website/react-magma-docs/src/pages/api/datagrid.mdx
Labels: ready for review

#847 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: ready for review

#841 feat(datagrid): Add `isSortableBySelected` prop to DataGrid, allowing tables to be sorted by the selected items.
  .changeset/datagrid_sortable.md
  .changeset/pre.json
  packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
  packages/react-magma-dom/src/components/Datagrid/Datagrid.test.js
  packages/react-magma-dom/src/components/Datagrid/Datagrid.tsx
  packages/react-magma-dom/src/components/Table/Table.stories.tsx
  packages/react-magma-dom/src/components/Table/Table.tsx
  packages/react-magma-dom/src/components/Table/TableRow.test.js
  packages/react-magma-dom/src/components/Table/TableRow.tsx
  website/react-magma-docs/src/pages/api/datagrid.mdx
Labels: high priority issue, ready for review
