Repository cengage/react-magma, pull requests merged in 2022-10, with the labels that each got.

#932 build(react-magma-icons): bump react-magma-icons to 2.3.4
  .changeset/icons-charts.md
  .changeset/icons-docs.md
  .changeset/icons-dom.md
  .changeset/icons-dropzone.md
  .changeset/icons-header.md
  .changeset/icons-schema.md
  package-lock.json
  packages/charts/package.json
  packages/dropzone/package.json
  packages/react-magma-dom/package-lock.json
  packages/react-magma-dom/package.json
  packages/schema-renderer/package.json
  patterns/header/package.json
  website/react-magma-docs/package.json
Labels: ready for review

#917 Feat/character counter
  .changeset/feat-characterCounter.md
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
  packages/react-magma-dom/src/components/CharacterCounter/index.ts
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/Input/Input.test.js
  packages/react-magma-dom/src/components/Input/index.tsx
  packages/react-magma-dom/src/components/InputBase/index.tsx
  packages/react-magma-dom/src/components/Textarea/Textarea.test.js
  packages/react-magma-dom/src/components/Textarea/index.tsx
  packages/react-magma-dom/src/i18n/default.ts
  packages/react-magma-dom/src/i18n/interface.ts
  packages/react-magma-dom/src/index.ts
  website/react-magma-docs/src/images/character-counter/behavior-1.png
  website/react-magma-docs/src/images/character-counter/behavior-2.png
  website/react-magma-docs/src/images/character-counter/behavior-3.png
  website/react-magma-docs/src/images/character-counter/intro-image.png
  website/react-magma-docs/src/pages/api/character-counter.mdx
  website/react-magma-docs/src/pages/api/input.mdx
  website/react-magma-docs/src/pages/api/textarea.mdx
  website/react-magma-docs/src/pages/design/character-counter.mdx
Labels: needs design feedback

#940 docs(table): Storybook example with adjustable number of rows
  .changeset/table-stories.md
  packages/react-magma-dom/src/components/Table/Table.stories.tsx
Labels: ready for review

#939 feat(button): subtle button color
  .changeset/subtle-button.md
  packages/react-magma-dom/src/components/Button/Button.stories.tsx
  packages/react-magma-dom/src/components/Button/index.tsx
  packages/react-magma-dom/src/components/ButtonGroup/index.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
  packages/react-magma-dom/src/components/StyledButton/StyledButton.test.js
  packages/react-magma-dom/src/components/StyledButton/index.tsx
  packages/react-magma-dom/src/components/StyledButton/styles.ts
  website/react-magma-docs/src/images/buttons/ex_6_1.png
  website/react-magma-docs/src/images/buttons/ex_6_4.png
  website/react-magma-docs/src/images/buttons/marketing_example.png
  website/react-magma-docs/src/images/buttons/subtle_button_example_1.png
  website/react-magma-docs/src/images/buttons/subtle_button_example_2.png
  website/react-magma-docs/src/pages/api/button.mdx
  website/react-magma-docs/src/pages/api/icon-button.mdx
  website/react-magma-docs/src/pages/design/button.mdx
Labels: ready for review

#913 fix(MultiCombobox): Support for `isClearable` button for multi comboboxes.
  .changeset/multicombobox-clearable.md
  packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
  packages/react-magma-dom/src/components/Combobox/Combobox.test.js
  packages/react-magma-dom/src/components/Combobox/Combobox.tsx
  packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx
  packages/react-magma-dom/src/components/Combobox/MultiCombobox.test.js
  packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
  packages/react-magma-dom/src/components/Combobox/index.tsx
  packages/react-magma-dom/src/components/Select/ItemsList.tsx
  packages/react-magma-dom/src/i18n/default.ts
  packages/react-magma-dom/src/i18n/interface.ts
  website/react-magma-docs/src/pages/api/combobox.mdx
Labels: ready for review, needs design feedback

#933 chore(npm/node): Update versions
  .changeset/update-versions-charts.md
  .changeset/update-versions-dropzone.md
  .changeset/update-versions-schema.md
  .changeset/update-versions.md
  package.json
  packages/charts/package-lock.json
  packages/dropzone/package-lock.json
  packages/schema-renderer/package-lock.json
  patterns/header/package-lock.json
  website/react-magma-docs/package-lock.json
Labels: ready for review

#950 Character Counter: a11y improvements
  .changeset/fix-characterCounter.md
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/Input/InputMessage.tsx
  packages/react-magma-dom/src/components/Input/index.tsx
Labels: ready for review
