Repository cengage/react-magma, pull requests merged in 2022-05, with the labels that each got.

#668 docs: update design guidelines images
  website/react-magma-docs/src/images/icons/icon-color-correct.png
  website/react-magma-docs/src/images/icons/icon-color-too-light.png
  website/react-magma-docs/src/images/icons/icon-mixed-colors.png
  website/react-magma-docs/src/images/icons/icon-sizes.png
  website/react-magma-docs/src/images/icons/icon-text-balance-correct.png
  website/react-magma-docs/src/images/icons/icon-text-balance-incorrect.png
  website/react-magma-docs/src/images/icons/icon-text-balance.png
  website/react-magma-docs/src/images/icons/icon-text-centered.png
  website/react-magma-docs/src/images/icons/icon-text-wrong-alignment.png
  website/react-magma-docs/src/images/icons/icons-intro.png
  website/react-magma-docs/src/images/layout/columns-12.png
  website/react-magma-docs/src/images/layout/columns-4.png
  website/react-magma-docs/src/images/layout/columns-6.png
  website/react-magma-docs/src/images/layout/columns-gutters-margins.png
  website/react-magma-docs/src/images/layout/gutters-16.png
  website/react-magma-docs/src/images/layout/gutters-24.png
  website/react-magma-docs/src/images/layout/layout-full-width.png
  website/react-magma-docs/src/images/layout/layout-restricted-width.png
  website/react-magma-docs/src/images/layout/layout-with-sidebar-1024.png
  website/react-magma-docs/src/images/layout/layout-with-sidebar.png
  website/react-magma-docs/src/images/spacing/icon-text-balance-correct.png
  website/react-magma-docs/src/images/spacing/spacing-example.png
  website/react-magma-docs/src/pages/design-intro/colors.mdx
  website/react-magma-docs/src/pages/design-intro/get-started.mdx
  website/react-magma-docs/src/pages/design-intro/icons.mdx
  website/react-magma-docs/src/pages/design-intro/layout.mdx
  website/react-magma-docs/src/pages/design/design-guidelines-styles.css
Labels: react-magma-docs, RM 3

#673 docs: update design guideline images
  .changeset/cuddly-jokes-guess.md
  website/react-magma-docs/src/images/accordion/accordion-anatomy.png
  website/react-magma-docs/src/images/accordion/accordion-bad-alignment.png
  website/react-magma-docs/src/images/accordion/accordion-crowded-icons.png
  website/react-magma-docs/src/images/accordion/accordion-drawer.png
  website/react-magma-docs/src/images/accordion/accordion-good-alignment.png
  website/react-magma-docs/src/images/accordion/accordion-in-page.png
  website/react-magma-docs/src/images/accordion/accordion-incorrect-icon-orientation.png
  website/react-magma-docs/src/images/accordion/accordion-incorrect-icons.png
  website/react-magma-docs/src/images/accordion/accordion-intro-example.png
  website/react-magma-docs/src/images/accordion/accordion-mouse-interaction.png
  website/react-magma-docs/src/images/accordion/accordion-sidebar.png
  website/react-magma-docs/src/images/accordion/accordion-states.png
  website/react-magma-docs/src/images/alerts/alert-anatomy.png
  website/react-magma-docs/src/images/alerts/alert-intro-image.png
  website/react-magma-docs/src/images/alerts/alert-severity-levels.png
  website/react-magma-docs/src/images/alerts/banner-alert-example.png
  website/react-magma-docs/src/images/alerts/batch-actions-toast.png
  website/react-magma-docs/src/images/alerts/inline-alert-example-2.png
  website/react-magma-docs/src/images/alerts/inline-alert-example.png
  website/react-magma-docs/src/images/alerts/mobile-banner-alert-example.png
  website/react-magma-docs/src/images/alerts/mobile-inline-alert-example.png
  website/react-magma-docs/src/images/alerts/mobile-toast-alert-example.png
  website/react-magma-docs/src/images/alerts/stack-toasts-incorrect.png
  website/react-magma-docs/src/images/alerts/toast-alert-example.png
  website/react-magma-docs/src/images/alerts/toast-error-manually-dismiss.png
  website/react-magma-docs/src/images/alerts/toast-successful-auto-dismiss.png
  website/react-magma-docs/src/images/badges/Badges.png
  website/react-magma-docs/src/images/badges/counter-example.png
  website/react-magma-docs/src/images/badges/label-colors.png
  website/react-magma-docs/src/images/badges/label-example.png
  website/react-magma-docs/src/images/breadcrumbs/breadcrumbs-wrap.png
  website/react-magma-docs/src/images/breadcrumbs/example-breadcrumbs.png
  website/react-magma-docs/src/pages/design/badges.mdx
Labels: react-magma-docs, RM 3

#665 feat(breadcrumb): updating breadcrumb colors
  .changeset/rebrand-breadcrumbs.md
  packages/react-magma-dom/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/react-magma-dom/src/components/Breadcrumb/BreadcrumbItem.tsx
  packages/react-magma-dom/src/components/Hyperlink/Hyperlink.test.js
  packages/react-magma-dom/src/components/Hyperlink/index.tsx
Labels: ready for review

#671 feat(progressbar): updating processBar colors
  .changeset/rebrand-processBar.md
  packages/react-magma-dom/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/react-magma-dom/src/components/ProgressBar/ProgressBar.test.js
  packages/react-magma-dom/src/components/ProgressBar/index.tsx
  website/react-magma-docs/src/pages/api/progress-bar.mdx
Labels: ready for review

#672 feat(badge): updating badge colors. Adding `isInverse` support
  .changeset/rebrand-badge.md
  packages/react-magma-dom/src/components/Badge/Badge.stories.tsx
  packages/react-magma-dom/src/components/Badge/Badge.test.js
  packages/react-magma-dom/src/components/Badge/index.tsx
Labels: ready for review

#666 feat(accordion): updating accordion with new colors
  .changeset/rebrand-accordion.md
  packages/react-magma-dom/src/components/Accordion/AccordionButton.tsx
  packages/react-magma-dom/src/components/Accordion/AccordionPanel.tsx
Labels: ready for review

#661 feat(buttons): adding in color changes throughout applicable components
  .changeset/afraid-coats-laugh.md
  packages/react-magma-dom/src/components/Accordion/Accordion.stories.tsx
  packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/react-magma-dom/src/components/Banner/Banner.test.js
  packages/react-magma-dom/src/components/Banner/index.tsx
  packages/react-magma-dom/src/components/Button/Button.stories.tsx
  packages/react-magma-dom/src/components/Button/Button.test.js
  packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
  packages/react-magma-dom/src/components/Button/index.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
  packages/react-magma-dom/src/components/Hyperlink/Hyperlink.stories.tsx
  packages/react-magma-dom/src/components/IconButton/IconButton.test.js
  packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
  packages/react-magma-dom/src/components/Pagination/PageButton.tsx
  packages/react-magma-dom/src/components/Pagination/Pagination.test.js
  packages/react-magma-dom/src/components/Pagination/Pagination.tsx
  packages/react-magma-dom/src/components/SkipLink/SkipLink.stories.tsx
  packages/react-magma-dom/src/components/SkipLink/SkipLink.test.js
  packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
  packages/react-magma-dom/src/components/StyledButton/StyledButton.test.js
  packages/react-magma-dom/src/components/StyledButton/index.tsx
  packages/react-magma-dom/src/components/StyledButton/styles.ts
  packages/react-magma-dom/src/theme/magma.ts
  website/react-magma-docs/src/components/ButtonProps/index.js
  website/react-magma-docs/src/components/IconButtonProps/index.js
  website/react-magma-docs/src/pages/api-intro/usage.mdx
  website/react-magma-docs/src/pages/api/accordion.mdx
  website/react-magma-docs/src/pages/api/button.mdx
  website/react-magma-docs/src/pages/api/dropdown.mdx
  website/react-magma-docs/src/pages/api/hyperlink.mdx
  website/react-magma-docs/src/pages/api/icon-button.mdx
  website/react-magma-docs/src/pages/api/skip-link.mdx
  website/react-magma-docs/src/pages/api/theme.mdx
  website/react-magma-docs/src/pages/api/toast.mdx
  website/react-magma-docs/src/pages/api/tooltip.mdx
Labels: ready for review

#678 fix(textarea): textarea has ability to be cleared
  .changeset/bug-textarea.md
  packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
  packages/react-magma-dom/src/components/Textarea/Textarea.test.js
  packages/react-magma-dom/src/components/Textarea/index.tsx
Labels: bug, ready for review

#682 build: Add pre-release file
  .changeset/pre.json
Labels: ready for review

#674 feat(tags): updating tags with new colors
  .changeset/rebrand-tags.md
  packages/react-magma-dom/src/components/Tag/Tag.stories.tsx
  packages/react-magma-dom/src/components/Tag/Tag.test.js
  packages/react-magma-dom/src/components/Tag/Tag.tsx
  website/react-magma-docs/src/pages/api/tag.mdx
Labels: ready for review

#679 feat(pagination): updates to V3 styling
  .changeset/thick-humans-give.md
  packages/react-magma-dom/src/components/Pagination/PageButton.tsx
  packages/react-magma-dom/src/components/Pagination/Pagination.stories.tsx
  packages/react-magma-dom/src/components/Pagination/Pagination.tsx
Labels: ready for review

#683 feat(dropzone): updating dropzone colors
  .changeset/rebrand-dropzone.md
  packages/dropzone/package-lock.json
  packages/dropzone/package.json
  packages/dropzone/src/components/dropzone/Dropzone.stories.tsx
  packages/dropzone/src/components/dropzone/Dropzone.test.js
  packages/dropzone/src/components/dropzone/Dropzone.tsx
  packages/dropzone/src/components/dropzone/FileIcon.tsx
  packages/dropzone/src/components/dropzone/Preview.tsx
Labels: needs-design-feedback

#696 docs: updated several pages
  .changeset/silent-kangaroos-watch.md
  website/react-magma-docs/src/images/inputs/combobox-example.png
  website/react-magma-docs/src/images/inputs/multi-select-example.png
  website/react-magma-docs/src/pages/design/dropdown.mdx
  website/react-magma-docs/src/pages/design/loading-indicators.mdx
  website/react-magma-docs/src/pages/design/modals.mdx
  website/react-magma-docs/src/pages/design/search.mdx
  website/react-magma-docs/src/pages/design/select.mdx
  website/react-magma-docs/src/pages/design/tables.mdx
  website/react-magma-docs/src/pages/design/tabs.mdx
Labels: react-magma-docs, RM 3, ready for review

#691 feat(heading): update heading expressive `contextVariant` styles
  .changeset/rebrand-expressive-docs.md
  .changeset/rebrand-expressive.md
  packages/react-magma-dom/src/components/Heading/Heading.stories.tsx
  packages/react-magma-dom/src/components/Heading/index.tsx
  packages/react-magma-dom/src/components/Paragraph/Paragraph.stories.tsx
  packages/react-magma-dom/src/components/Typography/index.tsx
  packages/react-magma-dom/src/theme/magma.ts
  website/react-magma-docs/src/components/Intro/IndexPageContent.js
  website/react-magma-docs/src/pages/api/theme.mdx
  website/react-magma-docs/src/pages/design-intro/typography.mdx
  website/react-magma-landing/templates/index.html
Labels: ready for review

#692 feat:(Dropdown) updates to v3 styling
  .changeset/rebrand-dropdowns.md
  packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownButton.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownDivider.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownHeader.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownMenuItem.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownMenuNavItem.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
Labels: ready for review

#722 docs(logo): update react magma logo
  .changeset/new-logo-docs.md
  .changeset/new-logo-landing.md
  website/react-magma-docs/gatsby-config.js
  website/react-magma-docs/src/components/FullLogo/index.js
  website/react-magma-docs/src/components/Logo/index.js
  website/react-magma-docs/src/images/React_Magma_Logo_Full.png
  website/react-magma-docs/src/images/hex-bg-1.png
  website/react-magma-docs/src/images/react-magma-icon.png
  website/react-magma-docs/src/images/react-magma-icon.svg
  website/react-magma-docs/src/images/volcano-icon.png
  website/react-magma-landing/static/images/react-magma-icon.png
  website/react-magma-landing/static/styles.css
  website/react-magma-landing/templates/index.html
Labels: ready for review, needs-design-feedback

#730 docs(breakpointscontainer): update breakpoints container examples
  .changeset/docs-breakpoints.md
  packages/react-magma-dom/src/components/BreakpointsContainer/BreakpointsContainer.stories.tsx
  website/react-magma-docs/src/pages/api/breakpoints-container.mdx
Labels: ready for review

#732 feat(combobox/select): update styling for items list inverse
  .changeset/combobox-spinner-inverse.md
  packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
  packages/react-magma-dom/src/components/Combobox/Combobox.tsx
  packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
  packages/react-magma-dom/src/components/Search/index.tsx
  packages/react-magma-dom/src/components/Select/ItemsList.tsx
  packages/react-magma-dom/src/components/Select/MultiSelect.tsx
  packages/react-magma-dom/src/components/Select/Select.tsx
  packages/react-magma-dom/src/components/Select/components.tsx
  packages/react-magma-dom/src/components/Select/shared.ts
  packages/react-magma-dom/src/components/Spinner/Spinner.stories.tsx
  packages/react-magma-dom/src/components/Spinner/index.tsx
  website/react-magma-docs/src/pages/api/spinner.mdx
Labels: ready for review

#645 Feature/header v3
  .changeset/popular-paws-serve.md
  packages/react-magma-dom/src/components/SkipLink/SkipLink.stories.tsx
  website/react-magma-docs/src/components/Intro/IndexPageContent.js
  website/react-magma-docs/src/components/MainContainer/index.js
  website/react-magma-docs/src/components/Masthead/index.js
  website/react-magma-docs/src/components/SlidingDrawer/index.js
Labels: ready for review

#719 feat(datepicker): update DatePicker with new colors
  .changeset/rebrand-datepicker.md
  packages/react-magma-dom/src/components/DatePicker/CalendarContext.ts
  packages/react-magma-dom/src/components/DatePicker/CalendarDay.tsx
  packages/react-magma-dom/src/components/DatePicker/CalendarHeader.tsx
  packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
  packages/react-magma-dom/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-magma-dom/src/components/DatePicker/HelperInformation.tsx
  packages/react-magma-dom/src/components/DatePicker/index.tsx
  website/react-magma-docs/src/pages/api/date-pickers.mdx
Labels: ready for review
