Repository cengage/react-magma, pull requests merged in 2023-05, with the labels that each got.

#1035 update theme documentation
  .changeset/theme-docs.md
  website/react-magma-docs/src/components/Donut/index.js
  website/react-magma-docs/src/pages/api-intro/custom-styles.mdx
  website/react-magma-docs/src/pages/api-intro/styles-and-themes.mdx
  website/react-magma-docs/src/pages/api/theme.mdx
Labels: ready for review

#1058 fix(combobox): Disabled Multi Combobox disables the buttons inside it
  .changeset/disabled-multiCombo.md
  packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
  packages/react-magma-dom/src/components/Combobox/MultiCombobox.test.js
  packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
  packages/react-magma-dom/src/components/Select/shared.ts
Labels: needs design feedback

#1062 docs: updated docs
  .changeset/great-donuts-build.md
  website/react-magma-docs/package-lock.json
  website/react-magma-docs/src/images/inputs/combobox-example.png
  website/react-magma-docs/src/images/inputs/multi-combobox-example.png
  website/react-magma-docs/src/images/inputs/native-select-example.png
  website/react-magma-docs/src/images/inputs/password-input-anatomy.png
  website/react-magma-docs/src/images/inputs/time-input-keyboard.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-alternate-colors.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-example.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-incorrect-multi-color.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-incorrect-neutral.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-inverse.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-parent-child-example.png
  website/react-magma-docs/src/images/selection-controls/Checkbox-states.png
  website/react-magma-docs/src/images/selection-controls/Radio-alternate-colors.png
  website/react-magma-docs/src/images/selection-controls/Radio-buttons-example.png
  website/react-magma-docs/src/images/selection-controls/Radio-example-2.png
  website/react-magma-docs/src/images/selection-controls/Radio-inverse.png
  website/react-magma-docs/src/images/selection-controls/Radio-select-only-one-incorrect.png
  website/react-magma-docs/src/images/selection-controls/Radio-select-only-one.png
  website/react-magma-docs/src/images/selection-controls/Radio-states.png
  website/react-magma-docs/src/images/selection-controls/Select-only-one-incorrect.png
  website/react-magma-docs/src/images/selection-controls/Select-only-one.png
  website/react-magma-docs/src/images/selection-controls/Selection-controls.png
  website/react-magma-docs/src/images/selection-controls/Toggle-switch-example.png
  website/react-magma-docs/src/images/selection-controls/Toggle-switch-states.png
  website/react-magma-docs/src/pages/design/alert.mdx
  website/react-magma-docs/src/pages/design/banner.mdx
  website/react-magma-docs/src/pages/design/checkboxes.mdx
  website/react-magma-docs/src/pages/design/combobox.mdx
  website/react-magma-docs/src/pages/design/indeterminate.mdx
  website/react-magma-docs/src/pages/design/input.mdx
  website/react-magma-docs/src/pages/design/native-select.mdx
  website/react-magma-docs/src/pages/design/password-input.mdx
  website/react-magma-docs/src/pages/design/radio.mdx
  website/react-magma-docs/src/pages/design/select.mdx
  website/react-magma-docs/src/pages/design/selection-controls.mdx
  website/react-magma-docs/src/pages/design/time-picker.mdx
  website/react-magma-docs/src/pages/design/toast.mdx
  website/react-magma-docs/src/pages/design/toggle.mdx
Labels: react-magma-docs

#1061 fix(CharacterCounter): Replace `maxLength` prop with `maxCount` and add `hasCharacterCounter` prop
  .changeset/fix-characterCounterProp.md
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
  packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
  packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/Input/Input.test.js
  packages/react-magma-dom/src/components/Input/InputMessage.tsx
  packages/react-magma-dom/src/components/Input/index.tsx
  packages/react-magma-dom/src/components/InputBase/index.tsx
  packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
  packages/react-magma-dom/src/components/Textarea/Textarea.test.js
  packages/react-magma-dom/src/components/Textarea/index.tsx
  website/react-magma-docs/src/pages/api/character-counter.mdx
  website/react-magma-docs/src/pages/api/input.mdx
  website/react-magma-docs/src/pages/api/textarea.mdx
Labels: ready for review
