Repository cengage/react-magma, pull requests merged in 2024-10, with the labels that each got.

#1455 fix(dropdown): Fix active index communication handled programmatically
  .changeset/a11y-dropdown-active-item.md
  packages/react-magma-dom/src/components/Dropdown/DropdownMenuItem.tsx
Labels: bug, a11y, ready for review

#1467 fix(drawer): Fix trapped focus in the drawer
  .changeset/a11y-drawer-navigation-focus.md
  packages/react-magma-dom/src/hooks/useFocusLock.ts
Labels: bug, a11y, ready for review

#1469 fix docs nested modal example
  .changeset/a11y-docs-Modal.md
  website/react-magma-docs/src/pages/api/modal.mdx
Labels: ready for review

#1468 fix gatsby empty image alts
  .changeset/a11y-docs-img-empty-alts.md
  website/react-magma-docs/src/pages/api-intro/page-templates.mdx
  website/react-magma-docs/src/pages/design-intro/layout.mdx
  website/react-magma-docs/src/pages/design-intro/spacing.mdx
  website/react-magma-docs/src/pages/design-intro/typography.mdx
  website/react-magma-docs/src/pages/design/accordion.mdx
  website/react-magma-docs/src/pages/design/alert.mdx
  website/react-magma-docs/src/pages/design/badge.mdx
  website/react-magma-docs/src/pages/design/banner.mdx
  website/react-magma-docs/src/pages/design/breadcrumb.mdx
  website/react-magma-docs/src/pages/design/button.mdx
  website/react-magma-docs/src/pages/design/buttongroup.mdx
  website/react-magma-docs/src/pages/design/card.mdx
  website/react-magma-docs/src/pages/design/character-counter.mdx
  website/react-magma-docs/src/pages/design/checkboxes.mdx
  website/react-magma-docs/src/pages/design/date-picker.mdx
  website/react-magma-docs/src/pages/design/dropdown.mdx
  website/react-magma-docs/src/pages/design/header.mdx
  website/react-magma-docs/src/pages/design/icon.mdx
  website/react-magma-docs/src/pages/design/indeterminate.mdx
  website/react-magma-docs/src/pages/design/input.mdx
  website/react-magma-docs/src/pages/design/list.mdx
  website/react-magma-docs/src/pages/design/loading-indicator.mdx
  website/react-magma-docs/src/pages/design/modal.mdx
  website/react-magma-docs/src/pages/design/password-input.mdx
  website/react-magma-docs/src/pages/design/progress-bar.mdx
  website/react-magma-docs/src/pages/design/radio.mdx
  website/react-magma-docs/src/pages/design/search.mdx
  website/react-magma-docs/src/pages/design/stepper.mdx
  website/react-magma-docs/src/pages/design/table.mdx
  website/react-magma-docs/src/pages/design/tabs.mdx
  website/react-magma-docs/src/pages/design/time-picker.mdx
  website/react-magma-docs/src/pages/design/toast.mdx
  website/react-magma-docs/src/pages/design/toggle.mdx
  website/react-magma-docs/src/pages/design/tooltip.mdx
  website/react-magma-docs/src/pages/design/tree-view.mdx
Labels: ready for review

#1464 chore(Lerna): Update Lerna and add local caching for build and test commands
  .changeset/build-upgrade-lerna.md
  .gitignore
  .nvmrc
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/charts/package.json
  packages/dropzone/package.json
  packages/react-magma-dom/scripts/generateJSON.js
Labels: ready for review

#1452 feat(Stepper): Add vertical orientation for `Stepper`.
  .changeset/a11y-Stepper-vertical-orientation.md
  packages/react-magma-dom/src/components/Stepper/ResponsiveStepperContainer.tsx
  packages/react-magma-dom/src/components/Stepper/Step.tsx
  packages/react-magma-dom/src/components/Stepper/Stepper.stories.tsx
  packages/react-magma-dom/src/components/Stepper/Stepper.test.js
  packages/react-magma-dom/src/components/Stepper/Stepper.tsx
  packages/react-magma-dom/src/components/Stepper/index.ts
  packages/react-magma-dom/src/index.ts
  website/react-magma-docs/src/pages/api/stepper.mdx
Labels: react-magma-dom, react-magma-docs, feature request, ready for review, storybook

#1471 fix(ProgressBar): Remove the animation if the user has a `prefers-reduced-motion` media query set.
  .changeset/a11y-progressBar-animation.md
  packages/react-magma-dom/src/components/ProgressBar/ProgressBar.test.js
  packages/react-magma-dom/src/components/ProgressBar/index.tsx
  packages/react-magma-dom/src/components/Select/SelectContainer.tsx
  website/react-magma-docs/src/pages/api/progress-bar.mdx
Labels: bug, react-magma-dom, react-magma-docs, a11y, ready for review

#1473 fix(ListItem, BlockQuote): fix colors respecting the `Theme` context
  .changeset/fix-blockQuote-border-color.md
  .changeset/fix-listItem-icons-color.md
  packages/react-magma-dom/src/components/BlockQuote/BlockQuote.stories.tsx
  packages/react-magma-dom/src/components/BlockQuote/BlockQuote.test.js
  packages/react-magma-dom/src/components/BlockQuote/BlockQuote.tsx
  packages/react-magma-dom/src/components/List/List.test.js
  packages/react-magma-dom/src/components/List/ListItem.tsx
Labels: bug, react-magma-dom, styles/theme, ready for review

#1474 fix(search): Fix the overlapping content issue around the clear button
  .changeset/search-clear-overlaps.md
  packages/react-magma-dom/src/components/InputBase/index.tsx
Labels: bug, ready for review

#1476 fix(useFocusLock): Fix the `useFocusLock` hook if the first or last element is disabled.
  .changeset/a11y-useFocusLock-hook-disabled-elements.md
  packages/react-magma-dom/src/components/Modal/Modal.stories.tsx
  packages/react-magma-dom/src/hooks/useFocusLock.test.js
  packages/react-magma-dom/src/hooks/useFocusLock.ts
Labels: bug, react-magma-dom, a11y, ready for review

#1482 fix(.srories.): Remove `.stories.` files from the production bundle.
  .changeset/fix-stories-files.md
  packages/react-magma-dom/tsconfig.json
Labels: react-magma-dom, builds, ready for review

#1485 A11y Documentation: Time Picker - Internationalization
  .changeset/a11y-timePicker-shortcut.md
  website/react-magma-docs/src/pages/api/time-picker.mdx
Labels: ready for review

#1479 fix(CheckBox): Fix for unreadable labels in `CheckBox` for screen readers.
  .changeset/a11y-checkBox-labels-not-read.md
  packages/react-magma-dom/src/components/Checkbox/index.tsx
Labels: bug, react-magma-dom, a11y, pc

#1480 feat(treeview): add support for isDisabled
  .changeset/feat-treeview-add-support-for-isdisabled.md
  packages/react-magma-dom/src/components/TreeView/TreeItem.test.js
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
  packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  packages/react-magma-dom/src/components/TreeView/utils.ts
  website/react-magma-docs/src/pages/api/tree-view.mdx
Labels: react-magma-dom, react-magma-docs, ready for review, storybook

#1487 fix(DatePicker): Fix navigation and accessibility issues.
  .changeset/a11y-datePicker-nav-issues.md
  packages/react-magma-dom/src/components/DatePicker/CalendarContext.ts
  packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
  packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
  packages/react-magma-dom/src/components/DatePicker/HelperInformation.test.js
  packages/react-magma-dom/src/components/DatePicker/HelperInformation.tsx
  packages/react-magma-dom/src/components/DatePicker/index.tsx
  packages/react-magma-dom/src/i18n/default.ts
Labels: bug, react-magma-dom, a11y, pc

#1492 fix(treeview): fix TreeView issues from verification
  .changeset/fix-treeview-issues-from-verification.md
  packages/react-magma-dom/jest.config.js
  packages/react-magma-dom/src/components/Checkbox/index.tsx
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  packages/react-magma-dom/src/components/TreeView/utils.ts
  packages/react-magma-dom/src/utils/index.ts
  packages/react-magma-dom/src/utils/utils.test.jsx
  website/react-magma-docs/src/pages/api/tree-view.mdx
Labels: react-magma-dom, react-magma-docs, ready for review

#1494 feat(Tabs, NavTabs): Add support for overwriting `TextTransform`.
  .changeset/feat-navTab-support-overwriting-textTransform.md
  packages/react-magma-dom/src/components/Drawer/Drawer.stories.tsx
  packages/react-magma-dom/src/components/NavTabs/NavTab.tsx
  packages/react-magma-dom/src/components/NavTabs/NavTabs.stories.tsx
  packages/react-magma-dom/src/components/NavTabs/NavTabs.test.js
  packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx
  packages/react-magma-dom/src/components/Tabs/Tab.tsx
  packages/react-magma-dom/src/components/Tabs/Tabs.stories.tsx
  packages/react-magma-dom/src/components/Tabs/Tabs.test.js
  packages/react-magma-dom/src/components/Tabs/Tabs.tsx
  packages/react-magma-dom/src/components/Tabs/TabsScrollSpyContainer.tsx
  packages/react-magma-dom/src/components/Tabs/shared.ts
  packages/react-magma-dom/src/index.ts
  website/react-magma-docs/src/pages/api/nav-tabs.mdx
  website/react-magma-docs/src/pages/api/tabs.mdx
Labels: ready for review

#1503 fix(Toast): Fixed loading ring alignment when zooming in Safari.
  .changeset/fix-toast-loading-ring-misaligned.md
  packages/react-magma-dom/src/components/ProgressRing/index.tsx
Labels: ready for review

#1505 Deprecate schema-renderer and header patterns
  .changeset/chore-deprecate-header.md
  .changeset/chore-deprecate-schema.md
  packages/schema-renderer/README.md
  patterns/header/README.md
  website/react-magma-docs/src/pages/api/schema-renderer.mdx
  website/react-magma-docs/src/pages/patterns/header.mdx
Labels: ready for review

#1514 fix(Breadcrumb): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
  .changeset/a11y-breadcrumb-hide-svg-from-screen-readers.md
  packages/react-magma-dom/src/components/Breadcrumb/Breadcrumb.test.js
  packages/react-magma-dom/src/components/Breadcrumb/BreadcrumbItem.tsx
Labels: ready for review

#1513 fix(CheckBox): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
  .changeset/a11y-checkbox-hide-svg-from-screen-readers.md
  packages/react-magma-dom/src/components/Checkbox/Checkbox.test.js
  packages/react-magma-dom/src/components/Checkbox/index.tsx
  packages/react-magma-dom/src/components/IndeterminateCheckbox/IndeterminateCheckbox.test.js
  packages/react-magma-dom/src/components/IndeterminateCheckbox/index.tsx
Labels: ready for review

#1516 fix(List): Hide SVGs from assistive tech by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
  .changeset/a11y-list-hide-icons-from-assistive-tech.md
  packages/react-magma-dom/src/components/List/List.test.js
  packages/react-magma-dom/src/components/List/ListItem.tsx
Labels: ready for review

#1515 fix(Dropdown): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `svg` elements.
  .changeset/a11y-dropdown-hide-svg-from-screen-readers.md
  packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
  packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/Dropdown/DropdownButton.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
  packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
  packages/react-magma-dom/src/components/IconButton/index.tsx
Labels: ready for review
