Repository cengage/react-magma, pull requests merged in 2024-11, with the labels that each got.

#1529 feat(Heading): Add a description of the `noTopMargin` and `noBottomMargin` props to the documentation.
  .changeset/feat-heading-add-props.md
  packages/react-magma-dom/src/components/Heading/Heading.stories.tsx
  packages/react-magma-dom/src/components/Heading/Heading.test.js
  website/react-magma-docs/src/pages/api/heading.mdx
Labels: ready for review

#1528 fix(DatePicker): Add `aria-label` to calendar header columns.
  .changeset/a11y-datepicker-calendar-header-columns.md
  packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
  website/react-magma-docs/src/pages/api/date-pickers.mdx
Labels: ready for review

#1527 docs: Update changelog to explain possible issue with emotion/css.
  .changeset/docs-emotion.md
  website/react-magma-docs/src/pages/api-intro/changelog.mdx
Labels: ready for review

#1539 fix(Select) Multi Select and Multi Combobox selected item focus outline
  .changeset/fix-select-combobox-multi-outline.md
  packages/react-magma-dom/src/components/Select/shared.ts
Labels: ready for review

#1533 feat(TreeView): onExpandedChange returns an array of expanded IDs
  .changeset/feat-treeview-onexpandedchange.md
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  packages/react-magma-dom/src/components/TreeView/utils.ts
  website/react-magma-docs/src/pages/api/tree-view.mdx
Labels: ready for review

#1548 docs: Fix contribution guidelines page
  .changeset/docs-contguidelines.md
  website/react-magma-docs/src/components/SubPageTabs/index.js
Labels: ready for review, blocks release

#1546 fix/Input: Fix HelpLink position on inputs.
  .changeset/fix-input-help-link.md
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/Input/Input.stories.tsx
  packages/react-magma-dom/src/components/Input/index.tsx
  packages/react-magma-dom/src/components/InputBase/index.tsx
  website/react-magma-docs/src/pages/api/input.mdx
Labels: needs design feedback

#1569 fix(Heading): Update margins for `heading2XLarge`
  .changeset/heading-margins.md
  packages/react-magma-dom/src/components/Heading/Heading.test.js
  packages/react-magma-dom/src/components/Heading/__snapshots__/Heading.test.js.snap
  packages/react-magma-dom/src/components/Typography/index.tsx
Labels: ready for review, needs design feedback

#1582 fix(Tag): Update tag focus state
  .changeset/tag-focus.md
  packages/react-magma-dom/src/components/Tag/Tag.stories.tsx
  packages/react-magma-dom/src/components/Tag/Tag.test.js
  packages/react-magma-dom/src/components/Tag/Tag.tsx
Labels: ready for review, blocks release

#1584 fix(TreeView): Fix invalid tree item children
  .changeset/tree-validity.md
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/utils.ts
Labels: bug, ready for review, blocks release
