Repository cengage/react-magma, pull requests merged in 2025-04, with the labels that each got.

#1720 TreeView: onExpandedChange Event Not Triggered During Keyboard Navigation & Retain expanded/collapsed state
  .changeset/feat-TreeView-retain-expanded-collapsed-state.md
  .changeset/fix-TreeView-keyboard.md
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
  packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  packages/react-magma-dom/src/components/TreeView/utils.ts
Labels: needs design feedback

#1712 chore(eslint): .lintstagedrc to lint mdx files in precommit hook
  .changeset/uuid copy.md
  .lintstagedrc
  website/react-magma-docs/src/pages/api/input.mdx
  website/react-magma-docs/src/pages/api/list.mdx
  website/react-magma-docs/src/pages/api/popover.mdx
  website/react-magma-docs/src/pages/api/skip-link.mdx
Labels: ready for review

#1729 feat(Popover): Add functionality to use `Esc` button, fix docs, add `maxWidth` to content
  .changeset/feat-popover-fix-comments.md
  packages/react-magma-dom/src/components/InputBase/index.tsx
  packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
  packages/react-magma-dom/src/components/Popover/Popover.tsx
  packages/react-magma-dom/src/components/Popover/PopoverContent.tsx
  packages/react-magma-dom/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/react-magma-dom/src/components/StyledButton/index.tsx
  website/react-magma-docs/src/pages/api/popover.mdx
Labels: needs design feedback

#1683 Input > Accessibility > Screenreader fix for Firefox when errorMessage and helperMessage exist simultaneously
  .changeset/inputFirefox.md
  packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
  packages/react-magma-dom/src/components/Input/Input.stories.tsx
  packages/react-magma-dom/src/components/Input/InputMessage.tsx
Labels: ready for review

#1742 chore(docs): update landing page
  .changeset/update-ladning-page.md
  website/react-magma-landing/scripts/build.js
  website/react-magma-landing/templates/_redirects
Labels: chore

#1739 fix(Dropdown): Displaying dropdown content under other elements.
  .changeset/fix-Dropdown-not-displayed-above-elements.md
  packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
Labels: ready for review, blocks release

#1747 fix(SkipLink): Deprecate `to` prop.
  .changeset/fix-SkipLink-deprecate-to-prop.md
  packages/react-magma-dom/src/components/SkipLink/index.tsx
Labels: ready for review, blocks release

#1740 chore: Add workflow to publish old docs & sync main -> dev
  .changeset/chore-deploy-old-workflow.md
  .changeset/update-ladning-page.md
  .github/workflows/publish-old.yml.disabled
  website/react-magma-landing/package.json
  website/react-magma-landing/scripts/build.js
Labels: ready for review
