Repository cengage/react-magma, pull requests merged in 2025-03, with the labels that each got.

#1658 fix(Pagination): Changed the ellipsis characters to an HTML entity for accessibility compliance.
  .changeset/fix-Pagination-screenreader.md
  packages/react-magma-dom/src/components/Pagination/Pagination.tsx
Labels: ready for review

#1667 fix(Pagination): Fix support for `page` in SimplePagination
  .changeset/simple-pag.md
  packages/react-magma-dom/src/components/Pagination/Pagination.stories.tsx
  packages/react-magma-dom/src/components/Pagination/SimplePagination.test.js
  packages/react-magma-dom/src/components/Pagination/SimplePagination.tsx
  website/react-magma-docs/src/pages/api/pagination.mdx
Labels: ready for review

#1663 feat(TreeView): add `expandAll` and `collapseAll`.
  .changeset/feat-TreeView-add-expandAll-and-collapseAll.md
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
  packages/react-magma-dom/src/components/TreeView/__snapshots__/TreeView.test.js.snap
  packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  website/react-magma-docs/src/pages/api/tree-view.mdx
Labels: ready for review, needs design feedback

#1636 feat/TreeView add isTopLevelSelectable prop
  .changeset/feat-treeview-is-top-level-selectable.md
  packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
  packages/react-magma-dom/src/components/TreeView/TreeView.test.js
  packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
  packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
  packages/react-magma-dom/src/components/TreeView/useTreeView.ts
  packages/react-magma-dom/src/components/TreeView/utils.ts
  website/react-magma-docs/src/pages/api/tree-view.mdx
Labels: ready for review

#1691 chore: update uuid support
  .changeset/uuid.md
  .storybook/main.js
  package-lock.json
  package.json
  packages/react-magma-dom/package.json
  packages/react-magma-dom/tsdx.config.js
  packages/schema-renderer/package.json
  patterns/header/package.json
  website/react-magma-docs/package.json
Labels: ready for review

#1595 feat(Popover): New `Popover` component
  .changeset/feat-popover.md
  package-lock.json
  packages/react-magma-dom/package.json
  packages/react-magma-dom/scripts/copy-changelog.js
  packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
  packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
  packages/react-magma-dom/src/components/Popover/Popover.test.js
  packages/react-magma-dom/src/components/Popover/Popover.tsx
  packages/react-magma-dom/src/components/Popover/PopoverContent.tsx
  packages/react-magma-dom/src/components/Popover/PopoverSection.tsx
  packages/react-magma-dom/src/components/Popover/PopoverTrigger.tsx
  packages/react-magma-dom/src/components/Popover/__snapshots__/Popover.test.js.snap
  packages/react-magma-dom/src/components/Popover/index.tsx
  packages/react-magma-dom/src/index.ts
  website/react-magma-docs/src/pages/api/dropdown.mdx
  website/react-magma-docs/src/pages/api/popover.mdx
  website/react-magma-docs/src/pages/design/dropdown.mdx
Labels: ready for review, needs design feedback

#1693 fix: fix dropzone ts path
  .changeset/dropzone-types.md
  packages/dropzone/package.json
Labels: ready for review

#1700 chore: Update to react-magma-icons v3.1.0
  .changeset/support-icons3-1.md
  package-lock.json
  packages/charts/package.json
  packages/dropzone/package.json
  packages/react-magma-dom/package.json
  packages/schema-renderer/package.json
  patterns/header/package.json
  website/react-magma-docs/package.json
Labels: ready for review

#1699 SkipLink: Should not accept "to" prop
  .changeset/fix-SkipLink-prop.md
  packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
  packages/react-magma-dom/src/components/SkipLink/SkipLink.stories.tsx
  packages/react-magma-dom/src/components/SkipLink/index.tsx
  website/react-magma-docs/src/pages/api/appbar.mdx
  website/react-magma-docs/src/pages/api/skip-link.mdx
Labels: ready for review

#1698 feat(Input): Support new types: `tel` and `url`
  .changeset/feat-Input-new-types.md
  packages/react-magma-dom/src/components/Input/Input.stories.tsx
  packages/react-magma-dom/src/components/Input/Input.test.js
  packages/react-magma-dom/src/components/InputBase/index.tsx
  website/react-magma-docs/src/pages/api/input.mdx
Labels: ready for review

#1707 feat(DefinitionList): New DefinitionList and DefinitionListItem components
  .changeset/feat-DefinitionList-DefinitionList.md
  packages/react-magma-dom/src/components/DefinitionList/DefinitionList.stories.tsx
  packages/react-magma-dom/src/components/DefinitionList/DefinitionList.test.js
  packages/react-magma-dom/src/components/DefinitionList/DefinitionList.tsx
  packages/react-magma-dom/src/components/DefinitionList/DefinitionListItem.tsx
  packages/react-magma-dom/src/components/DefinitionList/index.ts
  packages/react-magma-dom/src/components/List/ListItem.tsx
  packages/react-magma-dom/src/index.ts
  website/react-magma-docs/src/pages/api/list.mdx
Labels: react-magma-dom, a11y, ready for review

#1714 fix(Search): Style issues with clear and search icons
  .changeset/fix-Search-Update-icon-styles.md
  packages/react-magma-dom/src/components/InputBase/index.tsx
Labels: ready for review, needs design feedback

#1717 docs: Update version links in landing
  .changeset/landing-links.md
  website/react-magma-landing/templates/index.html
Labels: ready for review

#1710 fix(Dropdown): Expandable Menu Items > Icon missing at parent level
  .changeset/fix-Dropdown-add-icon-parent-level.md
  packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuListItem.tsx
Labels: ready for review

#1723 fix(Modal): Closing modals is slow
  .changeset/fix-Modal-closing-slow.md
  packages/react-magma-dom/src/components/Modal/Modal.tsx
Labels: ready for review

#1708 fix(tooltip): replace popper with floating-ui
  .changeset/fix-tooltip-replace-popper-with-floating-ui.md
  .cspell.json
  package-lock.json
  package.json
  packages/charts/package-lock.json
  packages/dropzone/package-lock.json
  packages/react-magma-dom/package-lock.json
  packages/react-magma-dom/package.json
  packages/react-magma-dom/src/components/Popover/Popover.tsx
  packages/react-magma-dom/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-magma-dom/src/components/Tooltip/Tooltip.test.js
  packages/react-magma-dom/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
  packages/react-magma-dom/src/components/Tooltip/index.tsx
  packages/react-magma-dom/src/theme/magma.ts
  packages/react-magma-dom/src/utils/index.ts
  packages/schema-renderer/package-lock.json
  patterns/header/package-lock.json
  website/react-magma-docs/package-lock.json
  website/react-magma-docs/package.json
  website/react-magma-docs/src/pages/api/tooltip.mdx
Labels: ready for review

#1724 fix(tabs): improve scroll functionality for smaller screens
  .changeset/fix-Tabs-Improve-functionality-small-screen.md
  packages/react-magma-dom/src/components/Tabs/TabsScrollSpyContainer.tsx
  packages/react-magma-dom/src/components/Tabs/utils.ts
Labels: ready for review
